---
- name: "Install forever (to run Node.js app)."
  npm: name=forever global=yes state=latest

#- name: "Check list of Node.js apps running."
#  command: forever list
#  register: forever_list
#  changed_when: false

#- name: "Start example Node.js app."
#  command: forever start /path/to/app.js
#  when: "forever_list.stdout.find('/path/to/app.js') == -1"